# Copyright 2023 iLogtail Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM sls-opensource-registry.cn-shanghai.cr.aliyuncs.com/ilogtail-community-edition/ilogtail-build-linux:2.0.3

ARG HOST_OS=Linux
ARG VERSION=2.0.0

USER root
WORKDIR /loongcollector

RUN mkdir -p /loongcollector/bin
RUN mkdir -p /loongcollector/lib
RUN mkdir -p /loongcollector/etc
RUN mkdir -p /loongcollector/log
RUN mkdir -p /loongcollector/data

COPY ./output/loongcollector /loongcollector/bin/loongcollector
COPY ./scripts/download_ebpflib.sh /tmp/

RUN chown -R $(whoami) /loongcollector && \
    chmod 755 /loongcollector/bin/loongcollector && \
    mkdir /loongcollector/data/checkpoint && \
    if [ `uname -m` = "x86_64" ]; then /tmp/download_ebpflib.sh /loongcollector/lib; fi && \
    rm /tmp/download_ebpflib.sh

COPY ./output/libPluginBase.so /loongcollector/lib/
COPY ./example_config/quick_start/loongcollector_config.json /loongcollector/bin/
COPY ./output/libPluginAdapter.so /loongcollector/lib/

ENV HOST_OS=$HOST_OS
ENV LOGTAIL_VERSION=$VERSION

EXPOSE 18689

ENTRYPOINT ["/loongcollector/bin/loongcollector"]
