FROM local/ilogtail-toolchain-linux-arm64 as dep-build

RUN curl -sSfL https://ilogtail-community-edition.oss-cn-shanghai.aliyuncs.com/toolchain/goc-v1.4.1-linux-arm64.tar.gz -o goc-v1.4.1-linux-arm64.tar.gz && \
    tar -xzf goc-v1.4.1-linux-arm64.tar.gz

RUN curl -sSfL https://ilogtail-community-edition.oss-cn-shanghai.aliyuncs.com/prebuilt-dependencies/ilogtail-deps.linux-arm64.tar.gz -o ilogtail-deps.linux-arm64.tar.gz && \
    tar -xzf ilogtail-deps.linux-arm64.tar.gz

FROM local/ilogtail-toolchain-linux-arm64
RUN mkdir -p /usr/local/bin /opt/logtail
# install goc for coverage
COPY --from=dep-build goc /usr/local/bin
# install c++ deps
COPY --from=dep-build ilogtail-deps.linux-arm64 /opt/logtail/deps

ARG USERNAME=admin
ARG USER_UID=500
ARG GROUPNAME=$USERNAME
ARG GROUP_GID=$USER_UID

# Create the user
RUN if getent passwd $USERNAME; then userdel -f $USERNAME; fi && \
    if getent group $GROUPNAME; then groupdel $GROUPNAME; fi && \
    groupadd --gid $GROUP_GID $USERNAME && \
    useradd --uid $USER_UID --gid $GROUP_GID -m $USERNAME && \
    echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME && \
    chmod 0440 /etc/sudoers.d/$USERNAME && \
    chown -R $USERNAME:$GROUPNAME $(eval echo ~$USERNAME) && \
    chmod 755 $(eval echo ~$USERNAME)

USER $USERNAME
