# Copyright 2021 iLogtail Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM centos:centos7.9.2009 as build
ARG HOST_OS=Linux
ARG VERSION=1.1.0
WORKDIR /output
COPY ilogtail-${VERSION}.tar.gz .
RUN tar -xzf ilogtail-${VERSION}.tar.gz

FROM centos:centos7.9.2009
ENV container docker
RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == \
systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*;\
rm -f /lib/systemd/system/anaconda.target.wants/*;
VOLUME [ "/sys/fs/cgroup" ]

RUN yum update -y && yum upgrade -y && yum -y clean all && rm -fr /var/cache && rm -rf /core.*

ARG HOST_OS=Linux
ARG VERSION=1.1.0
WORKDIR /usr/local/ilogtail

COPY --from=build /output/ilogtail-${VERSION}/* /usr/local/ilogtail/
COPY example_config/start_with_docker/ilogtail_config.json /usr/local/ilogtail/
COPY scripts/run_ilogtail.sh /usr/local/ilogtail/

RUN chmod -R 755 /usr/local/ilogtail/
RUN mkdir /usr/local/ilogtail/checkpoint

ENTRYPOINT ["/usr/local/ilogtail/run_ilogtail.sh"]
