FROM golang:1.19.10

RUN mkdir -p /tmp/loongcollector

WORKDIR /root
COPY . ./loongcollector

RUN apt-get update
RUN apt-get -y install python3-setuptools
RUN apt-get -y install python3-pip

WORKDIR /root/loongcollector/test
RUN pip3 install -r requirements.txt --break-system-packages

CMD ["sh", "-c", "while true; do sleep 3600; done"]