# Copyright 2024 iLogtail Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM --platform=$TARGETPLATFORM debian:bookworm as build
ARG VERSION=2.0.0
ARG TARGETPLATFORM
ARG UID=65532
WORKDIR /usr/local
COPY dist/loongcollector-${VERSION}.linux-*.tar.gz .
RUN tar -xzf loongcollector-${VERSION}.linux-${TARGETPLATFORM##*/}.tar.gz
RUN mv /usr/local/loongcollector-${VERSION} /usr/local/loongcollector && \
    mkdir -p /usr/local/loongcollector/data/checkpoint && \
    cp example_config/start_with_docker/loongcollector_config.json /usr/local/loongcollector/ && \
    chmod 755 /usr/local/loongcollector/loongcollector

FROM gcr.lank8s.cn/distroless/cc-debian12:latest
LABEL org.opencontainers.image.authors="yyuuttaaoo@gmail.com, jiangdeyan@gmail.com"

COPY --from=build /usr/lib/x86_64-linux-gnu/libuuid.so.1.3.0 /lib/x86_64-linux-gnu/libuuid.so.1

ARG HOST_OS=Linux
ARG VERSION=2.0.0
ARG TARGETPLATFORM

COPY --from=build --chown=$UID:$UID /usr/local/loongcollector /usr/local/loongcollector

WORKDIR /usr/local/loongcollector
RUN mkdir -p /usr/local/loongcollector/conf
RUN mkdir -p /usr/local/loongcollector/log
RUN mkdir -p /usr/local/loongcollector/data
RUN mkdir -p /usr/local/loongcollector/run

ENV HTTP_PROBE_PORT=7953 \
    ALIYUN_LOGTAIL_USER_DEFINED_ID=default \
    docker_file_cache_path=data/checkpoint/docker_path_config.json
CMD ["/usr/local/loongcollector/loongcollector"]