FROM --platform=$TARGETPLATFORM sls-opensource-registry.cn-shanghai.cr.aliyuncs.com/ilogtail-community-edition/centos7-cve-fix:1.0.0 as toolchain-build

ARG TARGETPLATFORM

# install dependencies
RUN sed -i \
    -e 's/^mirrorlist/#mirrorlist/' \
    -e 's/^#baseurl/baseurl/' \
    -e 's/mirror\.centos\.org/vault.centos.org/' \
    /etc/yum.repos.d/*.repo
RUN yum -y install epel-release centos-release-scl
RUN if [ "$TARGETPLATFORM" = "linux/amd64" ]; then \
    sed -i \
    -e 's/^mirrorlist/#mirrorlist/' \
    -e 's/^# baseurl/baseurl/' \
    -e 's/mirror\.centos\.org/vault.centos.org/' \
    /etc/yum.repos.d/CentOS-SCLo-scl.repo && \
    sed -i \
    -e 's/^mirrorlist/#mirrorlist/' \
    -e 's/^#baseurl/baseurl/' \
    -e 's/mirror\.centos\.org/vault.centos.org/' \
    /etc/yum.repos.d/CentOS-SCLo-scl-rh.repo; \
    elif [ "$TARGETPLATFORM" = "linux/arm64" ]; then \
    sed -i \
    -e 's/^mirrorlist/#mirrorlist/' \
    -e 's/^# baseurl/baseurl/' \
    -e 's/mirror\.centos\.org/vault.centos.org/' \
    -e 's/vault\.centos\.org\/centos/vault.centos.org\/altarch/' \
    /etc/yum.repos.d/CentOS-SCLo-scl.repo && \
    sed -i \
    -e 's/^mirrorlist/#mirrorlist/' \
    -e 's/^#baseurl/baseurl/' \
    -e 's/mirror\.centos\.org/vault.centos.org/' \
    -e 's/vault\.centos\.org\/centos/vault.centos.org\/altarch/' \
    /etc/yum.repos.d/CentOS-SCLo-scl-rh.repo; \
    else \
    echo "Unsupported platform"; \
    exit 1; \
    fi
RUN yum -y install devtoolset-9-gcc devtoolset-9-gcc-c++ make
RUN yum -y install curl-devel expat-devel gettext-devel openssl-devel perl-devel python3-devel zlib-devel \
    asciidoc xmlto docbook2X wget bison

# using gcc9
ENV MANPATH=/opt/rh/devtoolset-9/root/usr/share/man \
    PERL5LIB=/opt/rh/devtoolset-9/root//usr/lib64/perl5/vendor_perl:/opt/rh/devtoolset-9/root/usr/lib/perl5:/opt/rh/devtoolset-9/root//usr/share/perl5/vendor_perl \
    X_SCLS=devtoolset-9 \
    PCP_DIR=/opt/rh/devtoolset-9/root \
    LD_LIBRARY_PATH=/opt/rh/devtoolset-9/root/usr/lib64:/opt/rh/devtoolset-9/root/usr/lib:/opt/rh/devtoolset-9/root/usr/lib64/dyninst:/opt/rh/devtoolset-9/root/usr/lib/dyninst:/opt/rh/devtoolset-9/root/usr/lib64:/opt/rh/devtoolset-9/root/usr/lib \
    PATH=/usr/ali/bin:/opt/rh/devtoolset-9/root/usr/bin:$PATH \
    PYTHONPATH=/opt/rh/devtoolset-9/root/usr/lib64/python2.7/site-packages:/opt/rh/devtoolset-9/root/usr/lib/python2.7/site-packages \
    PKG_CONFIG_PATH=/opt/rh/devtoolset-9/root/usr/lib64/pkgconfig \
    INFOPATH=/opt/rh/devtoolset-9/root/usr/share/info

WORKDIR /

# prepare cmake
RUN [[ ${TARGETPLATFORM##*/} == 'amd64' ]] && ARCH='x86_64' || ARCH='aarch64' && \
    wget -nv https://ilogtail-community-edition.oss-cn-shanghai.aliyuncs.com/toolchain/cmake-3.23.2-linux-${ARCH}.tar.gz && \
    tar -xzf cmake-3.23.2-linux-${ARCH}.tar.gz && \
    mv cmake-3.23.2-linux-${ARCH} cmake-3.23.2
ENV CMAKE_ROOT=/cmake-3.23.2 \
    PATH=/cmake-3.23.2/bin:$PATH

# build clang
RUN wget -nv https://ilogtail-community-edition.oss-cn-shanghai.aliyuncs.com/toolchain/llvm-project-14.0.0.src.tar.xz && \
    tar -xf llvm-project-14.0.0.src.tar.xz && \
    mkdir llvm-project-14.0.0.src/build && \
    cd llvm-project-14.0.0.src/build && \
    cmake -G 'Unix Makefiles' -D CMAKE_C_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/gcc \
    -D CMAKE_CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/g++ \
    -D LLVM_ENABLE_PROJECTS='clang' \
    -D CMAKE_BUILD_TYPE=Release ../llvm && \
    make -sj$(nproc) clang-format && \
    cd /

# prepare go
RUN wget -nv https://ilogtail-community-edition.oss-cn-shanghai.aliyuncs.com/toolchain/go1.19.10.linux-${TARGETPLATFORM##*/}.tar.gz && \
    tar -xzf go1.19.10.linux-${TARGETPLATFORM##*/}.tar.gz

# prepare golangci-lint
RUN wget -nv https://ilogtail-community-edition.oss-cn-shanghai.aliyuncs.com/toolchain/golangci-lint-1.53.2-linux-${TARGETPLATFORM##*/}.tar.gz && \
    tar -xzf golangci-lint-1.53.2-linux-${TARGETPLATFORM##*/}.tar.gz && \
    mv golangci-lint-1.53.2-linux-${TARGETPLATFORM##*/} golangci-lint-1.53.2

FROM --platform=$TARGETPLATFORM sls-opensource-registry.cn-shanghai.cr.aliyuncs.com/ilogtail-community-edition/centos7-cve-fix:1.0.0

ARG TARGETPLATFORM

# install dev tool set and debug utilities
RUN sed -i \
    -e 's/^mirrorlist/#mirrorlist/' \
    -e 's/^#baseurl/baseurl/' \
    -e 's/mirror\.centos\.org/vault.centos.org/' \
    /etc/yum.repos.d/*.repo
RUN yum -y install centos-release-scl
RUN if [ "$TARGETPLATFORM" = "linux/amd64" ]; then \
    sed -i \
    -e 's/^mirrorlist/#mirrorlist/' \
    -e 's/^# baseurl/baseurl/' \
    -e 's/mirror\.centos\.org/vault.centos.org/' \
    /etc/yum.repos.d/CentOS-SCLo-scl.repo && \
    sed -i \
    -e 's/^mirrorlist/#mirrorlist/' \
    -e 's/^#baseurl/baseurl/' \
    -e 's/mirror\.centos\.org/vault.centos.org/' \
    /etc/yum.repos.d/CentOS-SCLo-scl-rh.repo; \
    elif [ "$TARGETPLATFORM" = "linux/arm64" ]; then \
    sed -i \
    -e 's/^mirrorlist/#mirrorlist/' \
    -e 's/^# baseurl/baseurl/' \
    -e 's/mirror\.centos\.org/vault.centos.org/' \
    -e 's/vault\.centos\.org\/centos/vault.centos.org\/altarch/' \
    /etc/yum.repos.d/CentOS-SCLo-scl.repo && \
    sed -i \
    -e 's/^mirrorlist/#mirrorlist/' \
    -e 's/^#baseurl/baseurl/' \
    -e 's/mirror\.centos\.org/vault.centos.org/' \
    -e 's/vault\.centos\.org\/centos/vault.centos.org\/altarch/' \
    /etc/yum.repos.d/CentOS-SCLo-scl-rh.repo; \
    else \
    echo "Unsupported platform"; \
    exit 1; \
    fi
RUN yum -y install devtoolset-9-gcc devtoolset-9-gcc-c++ devtoolset-9-libasan-devel make libuuid-devel libstdc++-static systemd-devel iproute gdb net-tools which wget vim tree man openssh-clients sudo openssl-devel zlib-devel

RUN yum -y clean all && rm -fr /var/cache && rm -rf /core.*
RUN if [ "$TARGETPLATFORM" = "linux/arm64" ]; then \
    sed -i \
    -e 's/debuginfo\.centos\.org\/centos/debuginfo.centos.org\/altarch/' \
    /etc/yum.repos.d/CentOS-SCLo-scl.repo && \
    sed -i \
    -e 's/debuginfo\.centos\.org\/centos/debuginfo.centos.org\/altarch/' \
    /etc/yum.repos.d/CentOS-SCLo-scl-rh.repo; \
    fi
RUN [[ ${TARGETPLATFORM##*/} == 'amd64' ]] && ARCH='x86_64' || ARCH='aarch64' && \
    debuginfo-install -y glibc-2.17-326.el7_9.${ARCH} libuuid-2.23.2-65.el7_9.1.${ARCH}

# install cmake
COPY --from=toolchain-build /cmake-3.23.2 /usr/

# install clang-format
COPY --from=toolchain-build /llvm-project-14.0.0.src/build/bin/clang-format /usr/bin/
RUN chmod +x /usr/bin/clang-format

# install golang
WORKDIR /
COPY --from=toolchain-build /go /usr/local/go
ENV GOROOT=/usr/local/go GOPATH=/opt/go PATH=/usr/local/go/bin:$PATH

# install golangci-lint
COPY --from=toolchain-build /golangci-lint-1.53.2/golangci-lint /opt/go/bin/

# install go language server
RUN go env -w GOPROXY="https://goproxy.cn,direct"
RUN go install golang.org/x/tools/gopls@v0.12.2 && \
    go install github.com/go-delve/delve/cmd/dlv@v1.20.2 && \
    go install github.com/josharian/impl@v1.2.0 && \
    go install github.com/fatih/gomodifytags@v1.16.0 && \
    go install github.com/cweill/gotests/gotests@v1.6.0 && \
    go install honnef.co/go/tools/cmd/staticcheck@v0.4.3

# using gcc9
ENV MANPATH=/opt/rh/devtoolset-9/root/usr/share/man \
    PERL5LIB=/opt/rh/devtoolset-9/root//usr/lib64/perl5/vendor_perl:/opt/rh/devtoolset-9/root/usr/lib/perl5:/opt/rh/devtoolset-9/root//usr/share/perl5/vendor_perl \
    X_SCLS=devtoolset-9 \
    PCP_DIR=/opt/rh/devtoolset-9/root \
    LD_LIBRARY_PATH=/opt/rh/devtoolset-9/root/usr/lib64:/opt/rh/devtoolset-9/root/usr/lib:/opt/rh/devtoolset-9/root/usr/lib64/dyninst:/opt/rh/devtoolset-9/root/usr/lib/dyninst:/opt/rh/devtoolset-9/root/usr/lib64:/opt/rh/devtoolset-9/root/usr/lib \
    PATH=/usr/ali/bin:/opt/rh/devtoolset-9/root/usr/bin:$PATH \
    PYTHONPATH=/opt/rh/devtoolset-9/root/usr/lib64/python2.7/site-packages:/opt/rh/devtoolset-9/root/usr/lib/python2.7/site-packages \
    PKG_CONFIG_PATH=/opt/rh/devtoolset-9/root/usr/lib64/pkgconfig \
    INFOPATH=/opt/rh/devtoolset-9/root/usr/share/info
