# Copyright 2021 iLogtail Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM --platform=$TARGETPLATFORM centos:centos7.9.2009 as build
ARG VERSION=0.0.1
ARG TARGETPLATFORM
WORKDIR /usr/local
COPY dist/loongcollector-${VERSION}.linux-*.tar.gz .
RUN tar -xzf loongcollector-${VERSION}.linux-${TARGETPLATFORM##*/}.tar.gz


FROM centos:centos7.9.2009
MAINTAINER TomYu yyuuttaaoo@gmail.com

ENV container docker


ARG TARGETPLATFORM

RUN if [ "$TARGETPLATFORM" = "linux/amd64" ]; then \
        echo "Building for AMD64"; \
        curl -L -o /etc/yum.repos.d/CentOS-Base.repo http://mirrors.aliyun.com/repo/Centos-7.repo; \
    elif [ "$TARGETPLATFORM" = "linux/arm64" ]; then \
        echo "Building for ARM64"; \
        curl -L -o /etc/yum.repos.d/CentOS-Base.repo http://mirrors.aliyun.com/repo/Centos-altarch-7.repo; \
    else \
        echo "Unsupported platform: $TARGETPLATFORM"; \
        exit 1; \
    fi


RUN yum update -y && yum upgrade -y && yum -y clean all && rm -fr /var/cache && rm -rf /core.*

ARG HOST_OS=Linux
ARG VERSION=0.0.1
ARG TARGETPLATFORM

COPY --from=build /usr/local/loongcollector-${VERSION} /usr/local/loongcollector
RUN chown -R $(whoami) /usr/local/loongcollector/ && \
    chmod 755 /usr/local/loongcollector/loongcollector && \
    mkdir -p /usr/local/loongcollector/data/checkpoint

WORKDIR /usr/local/loongcollector
RUN mkdir -p /usr/local/loongcollector/conf/instance_config/local
RUN mkdir -p /usr/local/loongcollector/log
RUN mkdir -p /usr/local/loongcollector/data
RUN mkdir -p /usr/local/loongcollector/run

COPY example_config/start_with_docker/loongcollector_config.json /usr/local/loongcollector/conf/instance_config/local/loongcollector_config.json
COPY scripts/loongcollector_control.sh /usr/local/loongcollector/

ENV HTTP_PROBE_PORT=7953 \
    ALIYUN_LOGTAIL_USER_DEFINED_ID=default \
    docker_file_cache_path=checkpoint/docker_path_config.json
CMD ["/usr/local/loongcollector/loongcollector_control.sh", "start_and_block"]
