# Copyright 2023 iLogtail Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM sls-opensource-registry.cn-shanghai.cr.aliyuncs.com/loongcollector-community-edition/loongcollector-build-linux:2.0.5

ARG HOST_OS=Linux
ARG VERSION=0.2.0

USER root
WORKDIR /loongcollector

RUN mkdir -p /loongcollector/conf/instance_config/local
RUN mkdir -p /loongcollector/log
RUN mkdir -p /loongcollector/data
RUN mkdir -p /loongcollector/run

COPY ./output/loongcollector /loongcollector/loongcollector/
COPY ./scripts/download_ebpflib.sh /tmp/

RUN chown -R $(whoami) /loongcollector && \
    chmod 755 /loongcollector/loongcollector && \
    mkdir /loongcollector/data/checkpoint && \
    if [ `uname -m` = "x86_64" ]; then /tmp/download_ebpflib.sh /loongcollector; fi && \
    rm /tmp/download_ebpflib.sh

COPY ./output/libGoPluginBase.so /loongcollector/
COPY ./example_config/quick_start/loongcollector_config.json /loongcollector/conf/instance_config/local/loongcollector_config.json
COPY ./output/libGoPluginAdapter.so /loongcollector/

ENV HOST_OS=$HOST_OS
ENV LOGTAIL_VERSION=$VERSION

EXPOSE 18689

ENTRYPOINT ["/loongcollector/loongcollector"]
