FROM local/ilogtail-toolchain-linux-amd64 as dep-build

RUN curl -sSfL https://ilogtail-community-edition.oss-cn-shanghai.aliyuncs.com/toolchain/goc-v1.4.1-linux-amd64.tar.gz -o goc-v1.4.1-linux-amd64.tar.gz && \
    tar -xzf goc-v1.4.1-linux-amd64.tar.gz

RUN curl -sSfL https://ilogtail-community-edition.oss-cn-shanghai.aliyuncs.com/prebuilt-dependencies/ilogtail-deps.linux-amd64.tar.gz -o ilogtail-deps.linux-amd64.tar.gz && \
    tar -xzf ilogtail-deps.linux-amd64.tar.gz

FROM local/ilogtail-toolchain-linux-amd64
RUN mkdir -p /usr/local/bin /opt/logtail
# install goc for coverage
COPY --from=dep-build goc /usr/local/bin
# install c++ deps
COPY --from=dep-build ilogtail-deps.linux-amd64 /opt/logtail/deps

