FROM python:3.8

RUN mkdir -p /tmp/loongcollector

WORKDIR /root
COPY . ./loongcollector

WORKDIR /root/loongcollector/test
RUN pip3 install -r requirements.txt

CMD ["sh", "-c", "while true; do sleep 3600; done"]