# Copyright 2021 iLogtail Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


FROM sls-registry.cn-beijing.cr.aliyuncs.com/sls-microservices/logtailplugin-base:1.16-goc as build

WORKDIR /src

COPY . .

RUN make cgobuild

FROM registry.cn-beijing.aliyuncs.com/log-service/logtail:v1.0.23.1-b012439-aliyun

RUN rm -f /usr/local/ilogtail/libPluginBase.so

COPY --from=build /src/bin/libPluginBase.so /usr/local/ilogtail/libPluginBase.so
