FROM sls-opensource-registry.cn-shanghai.cr.aliyuncs.com/ilogtail-community-edition/ilogtail-build-linux:2.0.3 as build

USER root
WORKDIR /backend

COPY . .

RUN go env -w GOPROXY="https://goproxy.cn,direct" \
    && go mod tidy

CMD sh -c "go build -o ConfigServer ./cmd && ./ConfigServer"


