FROM centos:7

RUN curl -L -o /etc/yum.repos.d/CentOS-Base.repo http://mirrors.aliyun.com/repo/Centos-7.repo \
    && yum update -y \
    && yum upgrade -y \
    && yum -y clean all \
    && rm -fr /var/cache \
    && rm -rf /core.* \
    && yum install -y gettext

WORKDIR /agent
COPY . .

CMD envsubst < ilogtail_config.template.json > ilogtail_config.json \
    && sh -c ./ilogtail > stdout.log 2> stderr.log



