version: '3.8'
services:
  mysql:
    image: mysql:latest
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    cap_add:
      - SYS_NICE
    networks:
      - server

  config-server:
    build:
      context: ${CONFIG_SERVER}
      dockerfile: Dockerfile
    # 如果之前构建过镜像，再次docker compose则不会重新构建
    image: config-server:nzh
    ports:
      - "9090:9090"
    environment:
      TZ: Asia/Shanghai
    networks:
      - server
    depends_on:
      - mysql

  agent:
    build:
      context: ${AGENT}
      dockerfile: Dockerfile-agent
    image: ilogtail:nzh
    environment:
      CONFIG_SERVER_ADDRESSES: '["config-server:9090"]'
      TZ: Asia/Shanghai
    deploy:
      replicas: 3
    networks:
      - server

#替换成你自己的网络
networks:
  server:
