apiVersion: v1
kind: Secret
metadata:
  name: ilogtail-secret
  namespace: ilogtail
type: Opaque
data:
  access_key:     # accesskey id if you want to flush to SLS
  access_key_id:  # accesskey secret if you want to flush to SLS
