# Copyright 2021 iLogtail Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Build Core

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'example_config/**'
      - 'docker/**'
      - 'k8s_template/**'
      - 'changes/**'
      - 'licenses/**'
      - 'CHANGELOG.md'
  push:
    branches:
      - main
      - 1.*

jobs:
  CI:
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 60
    strategy:
      matrix:
        go-version: [1.19]
        # https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idruns-on
        runner: [ arc-runner-set-ilogtail ]
      fail-fast: true
    steps:
      # Clean up space to prevent action from running out of disk space.
      - name: Free disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean
          sudo -E apt-get update
          sudo -E apt-get install -y libsystemd-dev build-essential git curl bc

      - name: Check disk space
        run: |
          df -hT $PWD

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
          
      - name: Check out code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build Binary
        env:
          BUILD_LOGTAIL_UT: OFF
          ENABLE_COMPATIBLE_MODE: ON
          ENABLE_STATIC_LINK_CRT: ON
          WITHOUTGDB: ON
          MAKE_JOBS: 24
        run: make core

      - name: Check compatibility
        env:
          BUILD_LOGTAIL_UT: OFF
          ENABLE_COMPATIBLE_MODE: ON
          ENABLE_STATIC_LINK_CRT: ON
          WITHOUTGDB: ON
        run: make dist && scripts/check_glibc.sh

  result:
    runs-on: arc-runner-set-ilogtail
    timeout-minutes: 60
    needs: [CI]
    steps:
      - name: Build Result
        run: echo "Just to make the GitHub merge button green"
